### ISSUE TITLE
Document testing in beadando_10

### ISSUE THREAD

**Issue by triszt4n** [poiuztrewq1/projlab_holy_oil#273]
**Please wait completing this task until all coding related issues are not solved.**

In beadando_8, we specified 41 testcases. These are already written in the input language in `testdir`: `test_*`. The expected results are also in the beadando_8. These tests then need to be ran and you need to compare the output with the expected one in beadando_8 (maybe not `res_*` !!!).

Once you've completely tested and documented the running of that test case, you can tick out it in this list.

# Berci @vercibar 
- [x] Settler builds Robot
- [x] Settler can't build Robot: not enough materials
- [x] Settler builds TeleportGate
- [x] Settler can't build TeleportGate: not enough materials
- [x] Settler can't build TeleportGate: not enough space
- [x] Settler places TeleportGate
- [x] Settler can't place TeleportGate: Asteroid has one already
- [x] Settler can't place TeleportGate: no TeleportGate in Storage
- [x] Asteroid chain explode with a robot on them

# Beni @poiuztrewq1 
- [x] Robots move
- [x] Ufos move
- [x] Teleporter moves
- [x] Settler moves
- [x] Settler can't move to Asteroid: not neighbours
- [x] Settler moves through TeleportGate
- [x] Settler can't move through TeleportGate: pair not placed
- [x] Sun pulls Water filled Asteroid nearby

# Ricsi @bercsenyirihi 
- [x] Asteroid explodes with a Robot on it
- [x] Asteroid explodes with a Settler and Ufo on it
- [x] Asteroid explodes with a TeleportGate on it
- [x] Asteroid explodes with everything on it
- [x] Two players mine Asteroid instantly
- [x] UFO steals resource from under Settler
- [x] Settler drills
- [x] Robot drills

# Emma @captEmma 
- [x] Settler mines Uranium
- [x] Settler can't mine: empty Asteroid
- [x] Settler can't mine: full Storage
- [x] Settler can't mine: layers remaining
- [x] Settler fills
- [x] Settler can't fill: not enough materials
- [x] Settler can't fill: Asteroid not empty
- [x] Sun pulls Uranium filled Asteroid nearby

# Trisztán @triszt4n 
- [x] Cause Sunstorm
- [x] Water evaporates
- [x] Water can't evaporate: layers remaining
- [x] Win game
- [x] Lose game
- [x] Game unwinnable
- [x] Replace uranium and explode with asteroid
- [x] Last neighbour explodes
